CREATE TABLE authors (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    bio TEXT,
    creado TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    contenido TEXT NOT NULL,
    autores_id INTEGER NOT NULL,
    published BOOLEAN DEFAULT FALSE,
    creado TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (autores_id) REFERENCES authors(id) ON DELETE CASCADE
);